import { GoogleGenAI } from "@google/genai";

export const STYLES = [
  "Chibi",
  "Pastel",
  "Minimalist",
  "3D Render",
  "Watercolor",
  "Pixel Art",
  "Yarn",
  "Sticker",
];

const getPromptForStyle = (style: string): string => {
  const base = "A cute, adorable image of Hornet from the game Hollow Knight";
  switch (style) {
    case "Chibi":
      return `${base}, in a chibi style, digital painting, holding her needle, detailed, vibrant colors.`;
    case "Pastel":
      return `${base}, in a soft, pastel-colored illustration, looking curious, whimsical fantasy art.`;
    case "Minimalist":
      return `Minimalist vector art of a cute Hornet from Hollow Knight on a dark, moody background.`;
    case "3D Render":
      return `A beautifully rendered 3D model of a cute, stylized Hornet from Hollow Knight, studio lighting, high detail.`;
    case "Watercolor":
      return `A watercolor painting of a cute Hornet from Hollow Knight, with a gentle expression and soft edges, paper texture.`;
    case "Pixel Art":
      return `Pixel art of Hornet from Hollow Knight in a cute pose, 16-bit retro style, detailed sprite.`;
    case "Yarn":
      return `A cute Hornet from Hollow Knight made of yarn, detailed textile art, macro photography, soft focus.`;
    case "Sticker":
      return `Hornet from Hollow Knight as a cute die-cut sticker, vibrant colors, glossy finish, white border.`;
    default:
      return `${base}, high quality digital art.`;
  }
};

export async function generateHornetImage(style: string): Promise<string> {
  // Assume process.env.API_KEY is available in the environment
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const prompt = getPromptForStyle(style);
  
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '1:1',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("The AI model failed to generate an image. Please check the console for more details.");
  }
}